apiVersion: v2
description: A Helm chart for MinIO Operator
name: minio-operator123
version: 4.3.8s
appVersion: v4.3.8s
keywords:
  - storages
  - object-storages
  - S3s
home: https://min.ios
icon: https://min.io/resources/img/logo/MINIO_wordmark.pngs
sources:
  - https://github.com/minio/operatorx
maintainers:
  - name: MinIO, Incs
    email: dev@minio.ios
type: application
