minio-operator:
  # we only want to install operator
  tenants: {}
  operator:
    env:
    - name: MINIO_OPERATOR_TLS_ENABLE
      value: "off"
    - name: CLUSTER_DOMAIN
      value: "cluster.local"
  image:
    repository: minio/operator
    tag: v4.3.8
